# Generated by Django 5.0.6 on 2024-08-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('firma', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('betreff', models.CharField(max_length=100)),
                ('nachricht', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KaufenForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(blank=True, max_length=100)),
                ('nachname', models.CharField(blank=True, max_length=100)),
                ('firma', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('betreff', models.CharField(blank=True, max_length=100)),
                ('strasse', models.CharField(blank=True, max_length=100)),
                ('hausnummer', models.CharField(blank=True, max_length=100)),
                ('plz', models.CharField(blank=True, max_length=100)),
                ('ort', models.CharField(blank=True, max_length=100)),
                ('nachricht', models.TextField(blank=True)),
                ('vorname_l', models.CharField(blank=True, max_length=100)),
                ('nachname_l', models.CharField(blank=True, max_length=100)),
                ('firma_l', models.CharField(blank=True, max_length=100)),
                ('telephone_l', models.CharField(blank=True, max_length=20)),
                ('email_l', models.EmailField(blank=True, max_length=254)),
                ('betreff_l', models.CharField(blank=True, max_length=100)),
                ('strasse_l', models.CharField(blank=True, max_length=100)),
                ('hausnummer_l', models.CharField(blank=True, max_length=100)),
                ('plz_l', models.CharField(blank=True, max_length=100)),
                ('ort_l', models.CharField(blank=True, max_length=100)),
                ('nachricht_l', models.TextField(blank=True)),
            ],
        ),
    ]
